### ISSUE TITLE
一直登录失败，可能是因为HUB系统换用了新版的统一认证登录系统。

### ISSUE THREAD

**Issue by jyxk** [MartinNey/hust-courses-to-ics#14]

**Comment by Kyle-Ye** [comment]
+1 ，我这边的完整日志如下
```
➜  hust-courses-to-ics git:(master) ✗ npm start

> node-hub@0.1.0 start /Volumes/MacWorkplace/Github/hust-courses-to-ics
> cd src && babel-node index.js --presets env

==== req ====>
 {
  "Referer": "pass.hust.edu.cn",
  "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
}
==== req ====>
==== status ====
 200
==== status ====
<==== res ====
 {
  "date": "Sat, 15 Feb 2020 07:53:40 GMT",
  "set-cookie": [
    "Language=zh_CN; expires=Sat, 22-Feb-2020 07:53:40 GMT; path=/",
    "JSESSIONID=7xNH1rvCnIKlSFgqTnmdpJZT-TvoYEGMxAkai_-OPFGSuwGtIYuh!156694723; path=/; HttpOnly",
    "BIGipServerpool-icdc-cas2=1828917420.25371.0000; path=/"
  ],
  "expires": "Thu, 01 Jan 1970 00:00:00 GMT"
}
<==== res ====
==== error ====
 Error: No public key found in pre sites: https://pass.hust.edu.cn/cas/login?service=http%3A%2F%2Fone.hust.edu.cn%2Fdcp%2Findex.jsp
    at genForm (/Volumes/MacWorkplace/Github/hust-courses-to-ics/src/index.js:27:15)
    at /Volumes/MacWorkplace/Github/hust-courses-to-ics/src/index.js:46:9
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
==== error ====
==== error ====
 请多尝试几次。如果还是不行则检查密码，如确定密码无误请发送 issue。
==== error ====
```
- 关键信息是 `No public key found in pre sites: https://pass.hust.edu.cn/cas/login?service=http%3A%2F%2Fone.hust.edu.cn%2Fdcp%2Findex.jsp`，

- 测试打印了一下发现这里publicKey是null，往回去打印data，发现data里面是get请求结果，data里面用这个正则表达式regex.publicKey `/RSAKeyPair\("([0-9]*?)","","([0-9a-fA-F]*?)"\);/g`搜索不到导致
```
// pre works, get init cookie
request(configs.preWork())
  .then(res => {
    Log.response(res)
    const genForm = data => {
      console.log(data)
      const publicKey = regex.publicKey.exec(data)
      if (!publicKey || publicKey.length < 2) {
        throw new Error(`Debug:${publicKey}\n No public key found in pre sites: ${configs.preWork()['url']}`)
      }
```
@MMMartt

**Comment by Kyle-Ye** [comment]
可能需要换一个能找到RSAKeyPair的url网站？

**Comment by MMMartt** [comment]
了解了，这两天看看

**Comment by ManiaciaChao** [comment]
新的CAS登录可以参考zcr的实现 [winderica/DailyReport](https://github.com/winderica/DailyReport)
