### ISSUE TITLE
Error opening data file ./eng.traineddata

### ISSUE THREAD

**Issue by Kyle-Ye** [MartinNey/hust-courses-to-ics#24]
## Error opening data file ./eng.traineddata

`npm start`运行后会报错,并会产生一个`eng.traineddata`文件

```
➜  hust-courses-to-ics git:(master) ✗ npm start

> node-hub@0.2.0 start /Users/kyle/Developer/hust-courses-to-ics
> babel-node src/index.js

==== node-hustpass ====
 logging in...
==== node-hustpass ====
Error opening data file ./eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
AdaptedTemplates != nullptr:Error:Assert failed:in file /workspace/tesseract/src/classify/adaptmatch.cpp, line 196
undefined
undefined
/Users/kyle/Developer/hust-courses-to-ics/node_modules/tesseract.js/src/createWorker.js:173
        throw Error(data);
        ^

Error: RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at ChildProcess.<anonymous> (/Users/kyle/Developer/hust-courses-to-ics/node_modules/tesseract.js/src/createWorker.js:173:15)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:485:12)
    at emit (internal/child_process.js:906:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hub@0.2.0 start: `babel-node src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hub@0.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kyle/.npm/_logs/2020-09-05T03_12_19_550Z-debug.log
```

eng.traineddata文件内容
```
<?xml version='1.0' encoding='utf-8' ?>
<Error>
	<Code>UnavailableForLegalReasons</Code>
	<Message>The appid is unavailable for legal reasons.</Message>
	<Resource>file-1252889006.cos.ap-guangzhou.myqcloud.com/tesseract/eng.traineddata.gz</Resource>
	<RequestId>NWY1MmQwYTRfNzQyZDdhNjRfYWU3N18xNDI0NGQ=</RequestId>
	<TraceId>OGVmYzZiMmQzYjA2OWNhODk0NTRkMTBiOWVmMDAxODc0OWRkZjk0ZDM1NmI1M2E2MTRlY2MzZDhmNmI5MWI1OTdjMDczODYwZjM5YTU3ZmZmOWI5MmY4NjkxY2I3MGNiMTZmYzA2N2QxZWU5MzkxNGQxNGZkZGE2OTAyOWUxMDA=</TraceId>
</Error>
```

## Other info
OS: macOS 11 beta6
npm@6.14.8
node v14.4.0

**Comment by Kyle-Ye** [comment]
Solved it with the help of node-hustpass' README.md

**Comment by Kyle-Ye** [comment]
`wget https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata` to get the model and remember to install imagemagick
